#!/bin/bash


if [ $# -ne 2 ]; then
    echo "Használat: prime [kezdőszám] [végsőszám]"
    exit 1
fi


if ! [[ "$1" =~ ^[0-9]+$ ]] || ! [[ "$2" =~ ^[0-9]+$ ]]; then
    echo "Hiba: Kérem adjon meg érvényes számokat!"
    exit 1
fi


/home/$(whoami)/cli-calculator/prime-code << EOF
$1
$2
EOF